apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastebin
  labels:
    app: pastebin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pastebin
  template:
    metadata:
      labels:
        app: pastebin
    spec:
      containers:
        - name: pastebin
          image: pastebin:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 20Mi
              cpu: "0.25"
            limits:
              memory: 1000Mi
              cpu: "1"
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017"
            - name: MEMCACHED_URL
              value: "memcached:11211"
          # readinessProbe:
          #   httpGet:
          #     path: /read/abc
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pastebin-service
spec:
  # type: LoadBalancer
  selector:
    app: pastebin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: ClientIP

---
