apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pastebin
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pastebin